### ISSUE TITLE
ATN website text updates

### ISSUE THREAD

**Issue by thcurtis** [ioos/atn-dac#37]
Please replace/update the text on ATN webpages as provided in the attached document (url's identified above each section in the document). Please ensure that Bill Woodward's (retired) name and contact info is removed from the website. Contact me with any questions. 

[ATN ioos.us website update Mar2023.docx](https://github.com/ioos/atn-dac/files/11019121/ATN.ioos.us.website.update.Mar2023.docx)
[atn_argos_request_2023.pdf](https://github.com/ioos/atn-dac/files/11019125/atn_argos_request_2023.pdf)

Thank you,
~~Tobey

**Comment by MathewBiddle** [comment]
This should be logged at https://github.com/ioos/atn-docs.

xref: https://github.com/ioos/atn-docs/issues/1
